"""
Sessions router
───────────────
A session represents one try-on attempt.
Works for BOTH anonymous (session_token) and authenticated (user_id) users.

Flow:
  1. POST /api/sessions/start   → create session, scrape product, run fit engine
  2. GET  /api/sessions/{id}    → poll status
  3. PATCH /api/sessions/{id}   → update selected size/color
"""

from fastapi import APIRouter, Header, HTTPException, BackgroundTasks
from typing import Optional
from uuid import uuid4

from models.schemas import (
    StartSessionRequest, SessionOut, ProductOut, FitResult,
    BodyMeasurements,
)
from services.product_extractor import extract_product
from services.fit_engine import calculate_fit, estimate_size_from_body
from services.user_service import get_measurements_for_session
from database.client import supabase

router = APIRouter()


def _optional_user_id(authorization: Optional[str]) -> Optional[str]:
    """Return user_id if valid JWT provided, else None (anonymous)."""
    if not authorization:
        return None
    token = authorization.replace("Bearer ", "").strip()
    try:
        res = supabase.auth.get_user(token)
        return res.user.id
    except Exception:
        return None


def _verify_session_owner(row: dict, user_id: Optional[str], session_token: Optional[str]) -> None:
    """Authenticated sessions require owner JWT; anonymous sessions require token."""
    row_user_id = row.get("user_id")

    if row_user_id:
        if not user_id:
            raise HTTPException(status_code=401, detail="Authentication required")
        if row_user_id != user_id:
            raise HTTPException(status_code=403, detail="Not your session")
        return

    if not session_token:
        raise HTTPException(status_code=401, detail="Session token required")
    if row.get("session_token") != session_token:
        raise HTTPException(status_code=403, detail="Invalid session token")


async def _process_session(session_id: str, url: str, measurements: BodyMeasurements):
    """Background task: extract product → run fit engine → update session."""
    db = supabase

    try:
        # 1. Extract product
        db.table("tryon_sessions").update({"status": "extracting"}).eq("id", session_id).execute()
        product = await extract_product(url)

        # Upsert product
        p_payload = {k: v for k, v in product.model_dump(exclude_none=True).items()}
        p_res = db.table("products").upsert(p_payload, on_conflict="url").execute()
        product_id = p_res.data[0]["id"] if p_res.data else None

        # 2. Run fit engine
        db.table("tryon_sessions").update({"status": "fitting"}).eq("id", session_id).execute()

        if product.size_chart:
            fit = calculate_fit(
                measurements=measurements,
                size_chart=product.size_chart,
                available_sizes=product.available_sizes,
                fit_preference=measurements.fit_preference or "regular",
            )
        else:
            # Fallback: estimate from height + weight
            est_size = estimate_size_from_body(
                measurements.height_cm or 170,
                measurements.weight_kg or 65,
                measurements.gender_category or "woman",
            )
            fit = FitResult(
                recommended_size=est_size,
                fit_score=0.6,
                fit_type="regular",
                warnings=[],
                details={},
            )

        # 3. Update session with results
        db.table("tryon_sessions").update({
            "status": "done",
            "product_id": product_id,
            "recommended_size": fit.recommended_size,
            "fit_score": float(fit.fit_score),
            "fit_type": fit.fit_type,
            "fit_warnings": [w.model_dump() for w in fit.warnings],
            "fit_details": fit.details,
            "selected_size": fit.recommended_size,
        }).eq("id", session_id).execute()

    except Exception as e:
        db.table("tryon_sessions").update({
            "status": "error",
            "error_message": str(e),
        }).eq("id", session_id).execute()


@router.post("/start", response_model=SessionOut)
async def start_session(
    req: StartSessionRequest,
    background_tasks: BackgroundTasks,
    authorization: Optional[str] = Header(default=None),
):
    """
    POST /api/sessions/start
    Works for both anonymous and authenticated users.

    Anonymous: pass session_token (UUID generated by the frontend).
    Authenticated: pass Authorization: Bearer <jwt>.

    If the user is authenticated and has saved measurements, they are loaded
    automatically and merged with any measurements provided in the request body.
    """
    user_id = _optional_user_id(authorization)

    # Load saved measurements if authenticated
    saved = await get_measurements_for_session(user_id)

    # Merge: request measurements override saved profile (user may update inline)
    merged = BodyMeasurements(**{
        **saved.model_dump(exclude_none=True),
        **(req.measurements.model_dump(exclude_none=True) if req.measurements else {}),
    })

    # Create session row (status = pending, product will be filled by background task)
    session_token = req.session_token or (None if user_id else str(uuid4()))
    payload = {
        "status": "pending",
        "user_id": user_id,
        "session_token": session_token,
        **{k: v for k, v in merged.model_dump().items() if v is not None},
    }
    res = supabase.table("tryon_sessions").insert(payload).execute()
    session_id = res.data[0]["id"]

    # Kick off background processing
    background_tasks.add_task(_process_session, session_id, req.product_url, merged)

    return SessionOut(id=session_id, status="pending")


@router.get("/{session_id}", response_model=SessionOut)
async def get_session(
    session_id: str,
    session_token: Optional[str] = None,
    authorization: Optional[str] = Header(default=None),
):
    """
    GET /api/sessions/{session_id}
    Poll this endpoint to check processing status.
    Anonymous users must supply ?session_token=... for ownership verification.
    """
    user_id = _optional_user_id(authorization)

    res = (
        supabase
        .table("tryon_sessions")
        .select("*, products(*)")
        .eq("id", session_id)
        .maybe_single()
        .execute()
    )
    if not res or not res.data:
        raise HTTPException(status_code=404, detail="Session not found")

    row = res.data

    _verify_session_owner(row, user_id, session_token)

    product_row = row.get("products")
    product = ProductOut(**product_row) if product_row else None

    fit_result = None
    if row.get("recommended_size"):
        fit_result = FitResult(
            recommended_size=row["recommended_size"],
            fit_score=row.get("fit_score", 0.5),
            fit_type=row.get("fit_type", "regular"),
            warnings=row.get("fit_warnings", []),
            details=row.get("fit_details", {}),
        )

    return SessionOut(
        id=session_id,
        status=row["status"],
        product=product,
        fit_result=fit_result,
        result_image_url=row.get("result_image_url"),
    )


@router.patch("/{session_id}")
async def update_session(
    session_id: str,
    selected_size: Optional[str] = None,
    selected_color: Optional[str] = None,
    session_token: Optional[str] = None,
    authorization: Optional[str] = Header(default=None),
):
    """PATCH /api/sessions/{session_id} — update selected size/color."""
    user_id = _optional_user_id(authorization)

    res = (
        supabase
        .table("tryon_sessions")
        .select("id, user_id, session_token")
        .eq("id", session_id)
        .maybe_single()
        .execute()
    )
    if not res or not res.data:
        raise HTTPException(status_code=404, detail="Session not found")

    _verify_session_owner(res.data, user_id, session_token)

    payload = {}
    if selected_size:
        payload["selected_size"] = selected_size
    if selected_color:
        payload["selected_color"] = selected_color

    if payload:
        supabase.table("tryon_sessions").update(payload).eq("id", session_id).execute()

    return {"ok": True}
